# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [29]:
x = torch.Tensor(5, 3)
print(x)

tensor([[9.6429e-39, 8.4490e-39, 9.6429e-39],
        [9.2755e-39, 1.0286e-38, 9.0919e-39],
        [8.9082e-39, 9.2755e-39, 8.4490e-39],
        [7.3469e-39, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0194e-38, 9.2755e-39]])


Construct a randomly initialized matrix

In [30]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8645, 0.9769, 0.6420],
        [0.1100, 0.0849, 0.9601],
        [0.8162, 0.9104, 0.6295],
        [0.5500, 0.1133, 0.1077],
        [0.9539, 0.0676, 0.6598]])


Get its size

In [19]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [20]:
x[1:3] = 2
print(x)

tensor([[0.7357, 0.5867, 0.6405],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.2150, 0.4766, 0.3476],
        [0.0736, 0.9668, 0.1317]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [15]:
# 1
t1 = torch.Tensor(2,17)
# 2
t2 = torch.FloatTensor(3,1)
# 3
t3 = torch.ones(5,2,1,dtype=torch.long)*7
print(t3)
# 4
t4 = torch.ByteTensor(5,)*0
t4[1:4] = 1
print(t4)

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])
tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [31]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.5681, 1.1725, 1.1679],
        [0.1364, 0.4686, 1.0960],
        [1.5526, 1.2265, 0.9158],
        [1.0390, 0.8675, 0.2107],
        [1.5799, 0.7635, 0.7573]])


### 2.2 Addition: syntax 2

In [32]:
print(torch.add(x, y))

tensor([[1.5681, 1.1725, 1.1679],
        [0.1364, 0.4686, 1.0960],
        [1.5526, 1.2265, 0.9158],
        [1.0390, 0.8675, 0.2107],
        [1.5799, 0.7635, 0.7573]])


### 2.3 Addition: giving an output tensor

In [33]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.5681, 1.1725, 1.1679],
        [0.1364, 0.4686, 1.0960],
        [1.5526, 1.2265, 0.9158],
        [1.0390, 0.8675, 0.2107],
        [1.5799, 0.7635, 0.7573]])


### 2.4 Addition: in-place

adds `x` to `y`

In [34]:
y.add_(x)
print(y)

tensor([[1.5681, 1.1725, 1.1679],
        [0.1364, 0.4686, 1.0960],
        [1.5526, 1.2265, 0.9158],
        [1.0390, 0.8675, 0.2107],
        [1.5799, 0.7635, 0.7573]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [35]:
print(x[:, 1])

tensor([0.9769, 0.0849, 0.9104, 0.1133, 0.0676])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [36]:
print('x=',x)
print('y=',y)
# 1
print(x*y)
print(torch.mul(x,y))
print(x.mul(y))

x= tensor([[0.8645, 0.9769, 0.6420],
        [0.1100, 0.0849, 0.9601],
        [0.8162, 0.9104, 0.6295],
        [0.5500, 0.1133, 0.1077],
        [0.9539, 0.0676, 0.6598]])
y= tensor([[1.5681, 1.1725, 1.1679],
        [0.1364, 0.4686, 1.0960],
        [1.5526, 1.2265, 0.9158],
        [1.0390, 0.8675, 0.2107],
        [1.5799, 0.7635, 0.7573]])
tensor([[1.3556, 1.1454, 0.7498],
        [0.0150, 0.0398, 1.0523],
        [1.2672, 1.1166, 0.5765],
        [0.5715, 0.0983, 0.0227],
        [1.5070, 0.0516, 0.4997]])
tensor([[1.3556, 1.1454, 0.7498],
        [0.0150, 0.0398, 1.0523],
        [1.2672, 1.1166, 0.5765],
        [0.5715, 0.0983, 0.0227],
        [1.5070, 0.0516, 0.4997]])
tensor([[1.3556, 1.1454, 0.7498],
        [0.0150, 0.0398, 1.0523],
        [1.2672, 1.1166, 0.5765],
        [0.5715, 0.0983, 0.0227],
        [1.5070, 0.0516, 0.4997]])


In [37]:
# 2
x.mul_(y)
print(x)

tensor([[1.3556, 1.1454, 0.7498],
        [0.0150, 0.0398, 1.0523],
        [1.2672, 1.1166, 0.5765],
        [0.5715, 0.0983, 0.0227],
        [1.5070, 0.0516, 0.4997]])


In [39]:
# 3
print('x=',x)
print('y=',y)
print(x/y)
print(torch.div(x,y))
print(x.div(y))
x.div_(y)
print(x)

x= tensor([[1.3556, 1.1454, 0.7498],
        [0.0150, 0.0398, 1.0523],
        [1.2672, 1.1166, 0.5765],
        [0.5715, 0.0983, 0.0227],
        [1.5070, 0.0516, 0.4997]])
y= tensor([[1.5681, 1.1725, 1.1679],
        [0.1364, 0.4686, 1.0960],
        [1.5526, 1.2265, 0.9158],
        [1.0390, 0.8675, 0.2107],
        [1.5799, 0.7635, 0.7573]])
tensor([[0.8645, 0.9769, 0.6420],
        [0.1100, 0.0849, 0.9601],
        [0.8162, 0.9104, 0.6295],
        [0.5500, 0.1133, 0.1077],
        [0.9539, 0.0676, 0.6598]])
tensor([[0.8645, 0.9769, 0.6420],
        [0.1100, 0.0849, 0.9601],
        [0.8162, 0.9104, 0.6295],
        [0.5500, 0.1133, 0.1077],
        [0.9539, 0.0676, 0.6598]])
tensor([[0.8645, 0.9769, 0.6420],
        [0.1100, 0.0849, 0.9601],
        [0.8162, 0.9104, 0.6295],
        [0.5500, 0.1133, 0.1077],
        [0.9539, 0.0676, 0.6598]])
tensor([[0.8645, 0.9769, 0.6420],
        [0.1100, 0.0849, 0.9601],
        [0.8162, 0.9104, 0.6295],
        [0.5500, 0.1133, 0.1077],
   

In [44]:
t1 = torch.rand(2,4)
t2 = torch.rand(4,2)
print('t1', t1)
print('t2', t2)
print(t1.matmul(t2)) # 2x4x4x2->2x2
print(torch.matmul(t1, t2))

t1 tensor([[0.1858, 0.1562, 0.3729, 0.9179],
        [0.1159, 0.8790, 0.0766, 0.1232]])
t2 tensor([[0.7598, 0.0657],
        [0.7537, 0.1035],
        [0.8555, 0.7637],
        [0.7103, 0.5534]])
tensor([[1.2299, 0.8211],
        [0.9036, 0.2253]])
tensor([[1.2299, 0.8211],
        [0.9036, 0.2253]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [45]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [46]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [47]:
a.add_(1)
print(a)
print(b)
# shallow copy here

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [48]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)
# shallow copy

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [50]:
# 1
import numpy as np
t1 = torch.ones(5,2)
print('tensor: ', t1)
print(type(t1))
# 2
np_t1 = t1.numpy()
print('numpy: ', np_t1)
print(type(np_t1))
# 3
t1 = torch.from_numpy(np_t1)
print('tensor: ', t1)
print(type(t1))

tensor:  tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
<class 'torch.Tensor'>
numpy:  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>
tensor:  tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
<class 'torch.Tensor'>


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [51]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[0.8645, 0.9769, 0.6420],
        [0.1100, 0.0849, 0.9601],
        [0.8162, 0.9104, 0.6295],
        [0.5500, 0.1133, 0.1077],
        [0.9539, 0.0676, 0.6598]], device='cuda:0')
tensor([[1.5681, 1.1725, 1.1679],
        [0.1364, 0.4686, 1.0960],
        [1.5526, 1.2265, 0.9158],
        [1.0390, 0.8675, 0.2107],
        [1.5799, 0.7635, 0.7573]], device='cuda:0')
tensor([[2.4326, 2.1494, 1.8099],
        [0.2463, 0.5534, 2.0561],
        [2.3688, 2.1369, 1.5453],
        [1.5890, 0.9808, 0.3184],
        [2.5338, 0.8311, 1.4171]], device='cuda:0')
